urlArgs: 'v=1.01'
# urlArgs: 'v=43'

paths:

  jquery: 'libs/jquery-1.11.0'
  isotope: 'libs/isotope.pkgd'
  react: 'libs/react-with-addons'
  backbone: 'libs/backbone'
  underscore: 'libs/underscore'

  # jquery: '//code.jquery.com/jquery-1.11.0.min'
  # react: '//cdnjs.cloudflare.com/ajax/libs/react/0.11.0/react-with-addons.min'
  # backbone: '//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min'
  # underscore: '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min'

  # Views - React components
  MainComponent: 'components/Main'
  HeaderComponent: 'components/Header'
  ContentComponent: 'components/Content'
  PhotosComponent: 'components/Photos'
  PhotoLargeComponent: 'components/PhotoLarge'
  AboutComponent: 'components/AboutComponent'
  ContactComponent: 'components/ContactComponent'
  FooterComponent: 'components/Footer'
  
  # React mixins
  ReactBackboneMixin: 'mixins/ReactBackbone'
  TelegraphMixin: 'mixins/Telegraph'
  TilesMixin: 'mixins/Tiles'

  # Extras
  BackboneRouter: 'extras/Router'
  YandexCounter: 'extras/YandexCounter'

  # Collections – Backbone
  AlbumsCollection: 'collections/Albums'
  PhotosCollection: 'collections/Photos'
  CamsCollection: 'collections/Cams'
  LensesCollection: 'collections/Lenses'

  # Models – Backbone
  AlbumModel: 'models/Album'
  PhotoModel: 'models/Photo'
  CamModel: 'models/Cam'
  LensModel: 'models/Lens'

shim:
  backbone:
    deps: ['jquery', 'underscore']
    exports: 'Backbone'
  isotope:
    deps: ['jquery']
    exports: 'Isotope'
  masonry:
    deps: ['jquery']
    exports: 'Masonry'
  jquery:
    exports: '$'
  underscore:
    exports: '_'

modules:
  - name: 'frontend'