urlArgs: 'v=4'

paths:

  jquery: '//code.jquery.com/jquery-1.11.0'
  react: '//cdnjs.cloudflare.com/ajax/libs/react/0.11.0/react-with-addons'
  backbone: '//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone'
  underscore: '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore'

  # jquery: '//code.jquery.com/jquery-1.11.0.min'
  # react: '//cdnjs.cloudflare.com/ajax/libs/react/0.11.0/react-with-addons.min'
  # backbone: '//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min'
  # underscore: '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min'

  # Views - React components
  MainComponent: 'components/Main'
  HeaderComponent: 'components/Header'
  ContentComponent: 'components/Content'
  PhotosComponent: 'components/Photos'
  FooterComponent: 'components/Footer'
  
  # React mixins
  ReactBackboneMixin: 'mixins/ReactBackbone'
  TelegraphMixin: 'mixins/Telegraph'

  # Collections – Backbone
  AlbumsCollection: 'collections/Albums'
  PhotosCollection: 'collections/Photos'

  # Models – Backbone
  AlbumModel: 'models/Album'
  PhotoModel: 'models/Photo'

shim:
  backbone:
    deps: ['jquery', 'underscore']
    exports: 'Blackbone'
  jquery:
    exports: '$'
  underscore:
    exports: '_'